### PR TITLE
Added navbar and footer

### PR DESCRIPTION
**Pull request by anubhav1206**
Added the navbar and footer. However there are so contrast related issues in the footer

### CODE REVIEW

**Comment by anshulsoni2010** [comment]
You have to some changes in font colors of Footer and there is issue in contact page navbar so you need to fix first them!

**Comment by anubhav1206** [comment]
Yeah I am trying

**Comment by anshulsoni2010** [comment]
I have fixed😅

**Comment by anubhav1206** [comment]
thanks

**Comment by anshulsoni2010** [comment]
wait sending you code

**Comment by anubhav1206** [comment]
its fine i got it

**Comment by anshulsoni2010** [comment]
add dark class in body tag

**Comment by anshulsoni2010** [comment]
and below code in above the closing body tag 

`script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>`

**Comment by anshulsoni2010** [comment]
After that I will merge your raised pr

**Comment by anubhav1206** [comment]
done, added.

**Pull request merged**
